{
 "title": "Temporal Spring Application Metrics (Manual)",
 "time": { "from": "2023-04-24T07:31:25.662Z", "to": "2023-04-24T07:45:34.234Z" },
 "panels": [
  {
   "title": "Workflow End 2 End Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sum by(hostname)(temporal_workflow_endtoend_latency_seconds_max{job=\"prometheus-spring-pods\"})  ",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Spring Workers Active Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sum by(hostname) (temporal_workflow_active_thread_count{job=\"prometheus-spring-pods\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Spring Activity Workers Task Slots Available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Slots" }
   ],
   "targets": [
    {
     "expr": "sum by(hostname) (temporal_worker_task_slots_available{job=\"prometheus-spring-pods\", worker_type=\"ActivityWorker\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Spring Workflow Workers Task Slots Available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Slots" }
   ],
   "targets": [
    {
     "expr": "sum by(hostname) (temporal_worker_task_slots_available{job=\"prometheus-spring-pods\", worker_type=\"WorkflowWorker\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Spring Workflow Task Schedule to Start (Sum)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sum by(hostname) (temporal_workflow_task_schedule_to_start_latency_seconds_sum{worker_type=\"WorkflowWorker\",job=\"prometheus-spring-pods\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Spring Workflow Task Schedule to Start (Max)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sum by(hostname) (temporal_workflow_task_schedule_to_start_latency_seconds_max{worker_type=\"WorkflowWorker\",job=\"prometheus-spring-pods\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Spring Activity Schedule to Start (Max)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sum by(activity_type) (temporal_activity_schedule_to_start_latency_seconds_max{job=\"prometheus-spring-pods\"})",
     "legendFormat": "{{activity_type}}"
    }
   ]
  },
  {
   "title": "Spring Activity Schedule to Start (Max)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sum by(activity_type) (temporal_activity_schedule_to_start_latency_seconds_max{job=\"prometheus-spring-pods\"})",
     "legendFormat": "{{activity_type}}"
    }
   ]
  },
  {
   "title": "Spring Temporal Workflow Cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sum by(hostname) (temporal_sticky_cache_size{job=\"prometheus-spring-pods\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Spring Temporal Workflow Active Threads Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "sum by(hostname) (temporal_workflow_active_thread_count{job=\"prometheus-spring-pods\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Server QoS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "((poll_success+poll_success_sync) /(poll_success + poll_success_sync + poll_timeouts))",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}