apiVersion: v1
kind: Pod
metadata: 
  name: shellbox
  namespace: default
spec:
  containers:
  - name: shellbox
    image: google/cloud-sdk
    command: ["sleep","60000"]
    volumeMounts:
    - name: keystore-certs
      mountPath: /etc/config/keystore
    - name: ca-keystore-certs
      mountPath: /etc/config/ca-keystore
    env:
      - name: KEYSTORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: custom-environment-secret
            key: keystore_password
  volumes:
  - name: keystore-certs
    secret:
      secretName: general-cert-secret
  - name: ca-keystore-certs
    secret:
      secretName: trust-manager-base-ca-secret
