apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: SetupResources
deploy: 
  kubectl:
    flags:
      disableValidation: false
manifests:
  rawYaml: 
    - minikube-setup-resources.yaml


---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: DeployCassandra
deploy: 
  helm:
    releases:
      - name: cass
        remoteChart: bitnami-repo/cassandra
        version: 10.5.1 # Version
        valuesFiles:
          - values-cassandra-on-multinode.yaml
portForward:
- resourceType: service
  resourceName: cass-cassandra
  namespace: default
  port: 9042
  localPort: 9042

---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: DeployElasticsearch
deploy: 
  helm:
    releases:
      - name: es
        remoteChart: elastic-repo/elasticsearch
        version: 7.17.3
        valuesFiles:
          - values-elasticsearch-on-multinode.yaml
portForward:
# https://192.168.1.205:9200/
- resourceType: service
  resourceName: es-elasticsearch-master
  namespace: default
  port: 9200
  localPort: 9200
  address: 0.0.0.0
---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: DeployPrometheus
deploy: 
  helm:
    releases:
      - name: pr
        remoteChart: prometheus-repo/prometheus
        valuesFiles:
          - values-prometheus-basic.yaml
portForward:
- resourceType: service
  resourceName: pr-prometheus-server
  namespace: default
  port: 80
  localPort: 18080


