# To be completed.

# Use an existing secret for the admin user.
admin:
  ## Name of the secret. Can be templated.
  existingSecret: "custom-environment-secret"
  userKey: GRAFANA_ADMIN_USER
  passwordKey: GRAFANA_ADMIN_PASSWORD

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: pr-prometheus-server
      type: prometheus
      url: http://pr-prometheus-server
#      access: proxy
      isDefault: true
#    - name: CloudWatch
#      type: cloudwatch
#      access: proxy
#      uid: cloudwatch
#      editable: false
#      jsonData:
#        authType: default
#        defaultRegion: us-east-1
#    deleteDatasources: []
#    - name: Prometheus
dashboardProviders: 
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

# 
# https://grafana.com/grafana/dashboards/
dashboards:
   default:
  #   some-dashboard:
  #     json: |
  #       $RAW_JSON
     kubernetes-cluster-monitoring:
       url: https://grafana.com/api/dashboards/315/revisions/3/download
       datasource: pr-prometheus-server
  #   prometheus-stats:
  #     gnetId: 2
  #     revision: 2
  #     datasource: Prometheus
  #   local-dashboard:
  #     url: https://example.com/repository/test.json
  #     token: ''