
#custom:
#  elasticsearch:
#      job:
#        enabled: false      # bug , if already setup , would fail with 400 Http Error.
#  curl:
#    cacert: "PENDING TODO"

# https://github.com/temporalio/helm-charts/blob/master/values.yaml

# Enable debug to ensure Job is not deleted after complettion. 
# "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
debug: true


server:
  replicaCount: 1
  dynamicConfig:
    matching.numTaskqueueReadPartitions:
    - value: 10
      constraints: {}
    matching.numTaskqueueWritePartitions:
    - value: 10
      constraints: {}
  config:
    logLevel: "debug,info"
    numHistoryShards: 512
    persistence:
      defaultStore: default
      visibilityStore: es-visibility
      # num history Shards
      default:
        driver: "cassandra"
        cassandra:
          hosts: ["cass-cassandra.default.svc.cluster.local"]
          port: 9042
          keyspace: temporal
          user: cassandra
          password: cGFzc3dvcmRmb3JBQzgyNjI4MTMxWFJS
          schemaDir: schema/cassandra/temporal/versioned
          replicationFactor: 1
          consistency:
            default:
              consistency: "local_quorum"
              serialConsistency: "local_serial"

      visibility:
        driver: "cassandra"
        cassandra:
          hosts: ["cass-cassandra.default.svc.cluster.local"]
          port: 9042
          keyspace: temporal_visibility
          user: cassandra
          password: cGFzc3dvcmRmb3JBQzgyNjI4MTMxWFJS
          schemaDir: schema/cassandra/visibility/versioned
          replicationFactor: 3
          consistency:
            default:
              consistency: "local_quorum"
              serialConsistency: "local_serial"

  archival:
    history:
      state: "enabled"
      enableRead: true
      provider: 
        filestore:
          fileMode: "0666"
          dirMode: "0766"
    visibility:
      state: "enabled"
      enableRead: true
      provider:
        filestore:
          fileMode: "0666"
          dirMode: "0766"
  namespaceDefaults:
    archival:
      history:
        state: "enabled"
        URI: "file:///tmp/temporal_archival/development"
      visibility:
        state: "enabled"
        URI: "file:///tmp/temporal_vis_archival/development"



cassandra:
  enabled: false
  # not deteted external: true

mysql:
  enabled: false

postgresql:
  enabled: false

# Using Custom Prometheus refer My README
prometheus:
  enabled: false

grafana:
  enabled: false

  
elasticsearch:
  enabled: true
# Stick to 1 , node affinity not spread is still an issue
  replicas: 1
# determins if es-index-setup is pre or post install.
  #external: false
  #host: "elasticsearch-master"
  # if using existing, set 
  external: true
  host: "es-elasticsearch-master"
  port: "9200"
  version: "v7"
  scheme: "https"
  logLevel: "info"
  username: "elastic"
  password: "cGFzc3dvcmRmb3JBQzgyNjI4MTMxWFJS"
  tls:
    enabled: true
    caFile: /mnt/tls/cert/ca.crt

disabledelasticsearch:
  enabled: true
  replicas: 3
  persistence:
    enabled: false
  imageTag: 7.17.3
  host: elasticsearch-master-headless
  scheme: http
  port: 9200
  version: "v7"
  logLevel: "error"
  username: ""
  password: ""
  visibilityIndex: "temporal_visibility_v1_dev"

web:
  enabled: true

schema:
  createDatabase:
    enabled: true
  setup:
    enabled: true
  update:
    enabled: true

# Changes need to add env for Postgres in server-job.yaml
#schema:
#  setup:
#    enabled: true
#    backoffLimit: 10
#  update:
#    enabled: true
#    backoffLimit: 10
