apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: PersistentVolumesSetup
deploy: 
  kubectl:
    flags:
      disableValidation: false
manifests:
  rawYaml: 
    - skaffold-persistent-volume_resources.yaml