apiVersion: v1
kind: Pod
metadata: 
  name: shellbox
  namespace: default
spec:
  containers:
  - name: shellbox
    image: google/cloud-sdk
#    image: temporalio/admin-tools
    command: ["sleep","60000"]
    volumeMounts:
    - name: keystore-certs
      mountPath: /etc/config/keystore
    - name: ca-certificates
      mountPath: /mnt/tls/cert/ca
    - name: temporal-certificates
      mountPath: /mnt/tls/cert/temporal
    - name: elasticsearch-certificates
      mountPath: /mnt/tls/cert/elasticsearch
    - name: cassandra-certificates
      mountPath: /mnt/tls/cert/cassandra
    env:
      - name: KEYSTORE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: custom-environment-secret
            key: keystore_password
  volumes:
  - name: keystore-certs
    secret:
      secretName: general-cert-secret
  - name: ca-certificates
    secret:
      secretName: trust-manager-base-ca-secret
  - name: temporal-certificates
    secret:
      secretName: temporal-cert-secret
  - name: elasticsearch-certificates
    secret:
      secretName: elasticsearch-cert-secret
  - name: cassandra-certificates
    secret:
      secretName: cassandra-cert-secret