# ##################### #
# Version Specific Config : 
#   https://github.com/elastic/helm-charts/blob/7.17/elasticsearch/README.md
#   https://github.com/elastic/helm-charts/blob/main/elasticsearch/README.md#configuration
# 

clusterName: "es-elasticsearch"
replicas: 3
# imageTag: 7.17.3
minimumMasterNodes: 1

# Removed Hard Affinity Rules
# refer https://github.com/elastic/helm-charts/tree/main/elasticsearch
# does not work seems primary and replicas cannot run on same node !!
antiAffinity: "soft"
nodeSelector:
    kubernetes.io/os: linux

service:
  type: ClusterIP

# Used by readiness, cannot turn off ssl in elasticsearch.yaml , pending.
protocol: https
persistence:
  enabled: true

# Elastic Password/secret to access service.
# CURL Authentication with --user elastic:123456 (new Password : cGFzc3dvcmRmb3JBQzgyNjI4MTMxWFJS)
extraEnvs:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: custom-environment-secret
        key: ELASTIC_PASSWORD

#secret:
#  enabled: true   # cant set to false, throws readiness probe ELASTIC_PASSWORD missing.
#  password: ""    # Used in Newer Version 8.x, empty generates a password
#  password: "123456"

esConfig:
  elasticsearch.yml: |
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
    xpack.security.enabled: true
    xpack.security.transport.ssl.enabled: true
    xpack.security.transport.ssl.verification_mode: none
    xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/keystore.p12
    xpack.security.transport.ssl.keystore.password: ${ES_KEYSTORE_PASSWORD}
    xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/truststore.p12
    xpack.security.transport.ssl.truststore.password: ${ES_KEYSTORE_PASSWORD}
    xpack.security.http.ssl.enabled: true
    xpack.security.http.ssl.truststore.path: /usr/share/elasticsearch/config/certs/truststore.p12
    xpack.security.http.ssl.truststore.password: ${ES_KEYSTORE_PASSWORD}
    xpack.security.http.ssl.keystore.path: /usr/share/elasticsearch/config/certs/keystore.p12
    xpack.security.http.ssl.keystore.password: ${ES_KEYSTORE_PASSWORD}

createCert: false
envFrom:
  - secretRef: 
      name: custom-environment-secret
secretMounts:
  - name: elastic-certificates
    secretName: elasticsearch-cert-secret
    path: /usr/share/elasticsearch/config/certs
  - name: ca-certificates
    secretName: trust-manager-base-ca-secret
    path: /usr/share/elasticsearch/config/ca-trust



resources:
  requests:
    cpu: "1000m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "512Mi"

#resources:
#  requests:
#    cpu: "1000m"
#    memory: "2Gi"
#  limits:
#    cpu: "1000m"
#    memory: "2Gi"