prometheus:
  server:
    persistentVolume:
      enabled: true
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
#          volumeName: pr-persistent-volume
          storageClassName: manual
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
          selector:
            matchLabels:
              app.kubernetes.io/name: "prometheus-pv"
podLabels:
  "app.kubernetes.io/instance": "tio"