apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: AppSpringBootResources
deploy: 
  kubectl:
    flags:
      disableValidation: false
manifests:
  rawYaml: 
    - skaffold-spring-boot-app_resources.yaml

---
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: DeploySpringBootApp
deploy: 
  helm:
    releases:
      - name: spring-boot-app
        chartPath: ../spring-boot-app/helm
portForward:
- resourceType: service
  resourceName: spring-boot-app
  namespace: default
  port: 80
  localPort: 18080
  address: 0.0.0.0
