clusterName: "es-elasticsearch"
replicas: 1
# imageTag: 7.17.3
minimumMasterNodes: 1

# Removed Hard Affinity Rules
# refer https://github.com/elastic/helm-charts/tree/main/elasticsearch
# does not work seems primary and replicas cannot run on same node !!
antiAffinity: "soft"
nodeSelector:
    kubernetes.io/os: linux

service:
  type: ClusterIP

# Used by readiness, cannot turn off ssl in elasticsearch.yaml , pending.
protocol: https
persistence:
  enabled: true

secret:
  enabled: true
# password: "" 
  password: "123456"

esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false
    xpack.security.enrollment.enabled: false
    xpack.security.http.ssl:
      enabled: false
    xpack.security.transport.ssl:
      enabled: false


resources:
  requests:
    cpu: "1000m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "512Mi"

#resources:
#  requests:
#    cpu: "1000m"
#    memory: "2Gi"
#  limits:
#    cpu: "1000m"
#    memory: "2Gi"