clusterName: "es-elasticsearch"
replicas: 1
# imageTag: 7.17.3
minimumMasterNodes: 1

# Removed Hard Affinity Rules
# refer https://github.com/elastic/helm-charts/tree/main/elasticsearch
# does not work seems primary and replicas cannot run on same node !!
antiAffinity: "soft"
nodeSelector:
    kubernetes.io/os: linux
service:
  type: ClusterIP

#protocol: http
persistence:
  enabled: true

secret:
  enabled: true
  password: ""

resources:
  requests:
    cpu: "1000m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "512Mi"

#resources:
#  requests:
#    cpu: "1000m"
#    memory: "2Gi"
#  limits:
#    cpu: "1000m"
#    memory: "2Gi"