clusterName: "es-elasticsearch"
replicas: 1
# imageTag: 7.17.3
minimumMasterNodes: 1

# Removed Hard Affinity Rules
# refer https://github.com/elastic/helm-charts/tree/main/elasticsearch
# does not work seems primary and replicas cannot run on same node !!
antiAffinity: "soft"
nodeSelector:
    kubernetes.io/os: linux

service:
  type: ClusterIP

# Used by readiness, cannot turn off ssl in elasticsearch.yaml , pending.
protocol: https
persistence:
  enabled: true

# CURL Authentication with --user elastic:123456 
secret:
  enabled: true  # cant set to false, throws readiness probe ELASTIC_PASSWORD missing.
# password: "" 
  password: "123456"

esConfig:
  elasticsearch.yml: |
    # https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
    xpack.security.enabled: true
    xpack.security.transport.ssl.enabled: true
    xpack.security.transport.ssl.verification_mode: certificate
    xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/keystore.p12
    xpack.security.transport.ssl.keystore.password: ${ES_KEYSTORE_PASSWORD}
    xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/truststore.p12
    xpack.security.transport.ssl.truststore.password: ${ES_KEYSTORE_PASSWORD}
    xpack.security.http.ssl.enabled: true
    xpack.security.http.ssl.truststore.path: /usr/share/elasticsearch/config/certs/truststore.p12
    xpack.security.http.ssl.truststore.password: ${ES_KEYSTORE_PASSWORD}
    xpack.security.http.ssl.keystore.path: /usr/share/elasticsearch/config/certs/keystore.p12
    xpack.security.http.ssl.keystore.password: ${ES_KEYSTORE_PASSWORD}

createCert: false
envFrom:
  - secretRef: 
      name: custom-environment-secret
secretMounts:
  - name: elastic-certificates
    secretName: elasticsearch-cert-secret
    path: /usr/share/elasticsearch/config/certs
  - name: ca-certificates
    secretName: trust-manager-base-ca-secret
    path: /usr/share/elasticsearch/config/ca-trust



resources:
  requests:
    cpu: "1000m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "512Mi"

#resources:
#  requests:
#    cpu: "1000m"
#    memory: "2Gi"
#  limits:
#    cpu: "1000m"
#    memory: "2Gi"