volumePermissions:
    enabled: true
auth:
  existingSecret: single-use-dev-secrets
primary:
  nodeSelector:
    kubernetes.io/hostname: mknode-m02
  persistence:
    enabled: true
    existingClaim: "pg-persistent-volume-claim"