
# Disable PV when running in multi-node some issue.
server:
  persistentVolume:
    enabled: false
    existingClaim: "pr-persistent-volume-claim"
    mountPath: "/mnt/host/pv-prometheus-data"
    size: 2Gi
    storageClass: manual

# Refer https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config
# TODO Add Filtering based on label and metadata
extraScrapeConfigs: |
  - job_name: 'prometheus-spring-service'
    honor_labels: true
    kubernetes_sd_configs:
      - role: service
    metrics_path: /actuator/prometheus
  - job_name: 'prometheus-spring-pods'
    honor_labels: true
    kubernetes_sd_configs:
      - role: pod
    metrics_path: /actuator/prometheus
    