app:
  config:
    temporal:
      tio1:
        name: tio1
        target: localhost:7233
        namespace: fastns
        task-queue: "SIMPLE_TASK_QUEUE"
        use-search-attribute: false


server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"