apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: benchmark
    component: workers
  name: benchmark-workers
spec:
  replicas: 10
  selector:
    matchLabels:
      app: benchmark
      component: workers
  template:
    metadata:
      labels:
        app: benchmark
        component: workers
    spec:
      containers:
      - image: ghcr.io/temporalio/benchmark-workers:main
        imagePullPolicy: Always
        name: benchmark-workers
        env:
        - name: TEMPORAL_GRPC_ENDPOINT
          value: "tio1-temporal-frontend:7233"
        - name: TEMPORAL_NAMESPACE
          value: "default"
        - name: TEMPORAL_TASK_QUEUE
          value: "benchmark"
        - name: TEMPORAL_WORKFLOW_TASK_POLLERS
          value: "16"
        - name: TEMPORAL_WORKFLOW_ACTIVITY_TASK_POLLERS
          value: "8"
        - name: PROMETHEUS_ENDPOINT
          value: "0.0.0.0:8081"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: benchmark
    component: workers
  name: svc-benchmark-workers
spec:
  selector:
    app: benchmark
    component: workers
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: benchmark
    component: soak-test
  name: benchmark-soak-test
spec:
  replicas: 0
  selector:
    matchLabels:
      app: benchmark
      component: soak-test
  template:
    metadata:
      labels:
        app: benchmark
        component: soak-test
    spec:
      containers:
      - image: ghcr.io/temporalio/benchmark-workers:main
        imagePullPolicy: Always
        name: benchmark-soak-test
        env:
        - name: TEMPORAL_GRPC_ENDPOINT
          value: "tio1-temporal-frontend:7233"
        - name: TEMPORAL_NAMESPACE
          value: "default"
        - name: TEMPORAL_TASK_QUEUE
          value: "benchmark"
        - name: CONCURRENT_WORKFLOWS
          value: "10000"
        command: ["runner", "-w", "-c", "$(CONCURRENT_WORKFLOWS)", "-t", "ExecuteActivity", '{ "Count": 3, "Activity": "Echo", "Input": { "Message": "test" } }']
      restartPolicy: Always