volumePermissions:
    enabled: true
auth:
  existingSecret: single-use-dev-secrets
primary:
  nodeSelector:
#    kubernetes.io/region: uk
    kubernetes.io/os: linux
  persistence:
    enabled: true
    existingClaim: "pg-persistent-volume-claim"